@echo off
echo Starting Marketing Campaign Data Quality Agent Backend...
cd backend
echo Installing Python dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
python main.py
pause