@echo off
echo Starting Marketing Campaign Data Quality Agent Frontend...
cd frontend
echo Installing Node.js dependencies...
npm install
echo Starting React development server...
npm start
pause